image: debian:stable

linux-binaries:
  script:
    - apt update && apt -y install build-essential libgtk2.0-dev libpulse-dev mesa-common-dev libgtksourceview2.0-dev libcairo2-dev libsdl1.2-dev libxv-dev libao-dev libopenal-dev libudev-dev
    - make -C icarus compiler=g++
    - make -C higan compiler=g++
    - sed -i -e 's/id -un/echo not-root/' higan/target-tomoko/GNUmakefile
    - mkdir -p artifacts/bin
    - mkdir -p artifacts/share/applications
    - make -C icarus prefix=../artifacts install
    - make -C higan prefix=../artifacts install
  artifacts:
    paths:
      - artifacts/*
  cache:
    paths:
      - icarus/obj/*.o
      - higan/obj/*.o
