image: debian:stable

linux-binaries:
  script:
    - apt update && apt -y install build-essential libgtk2.0-dev libpulse-dev mesa-common-dev libgtksourceview2.0-dev libcairo2-dev libsdl1.2-dev libxv-dev libao-dev libopenal-dev libudev-dev
    - make -C icarus compiler=g++
    - make -C higan compiler=g++
    - sed -i -e 's/id -un/echo not-root/' higan/target-tomoko/GNUmakefile
    - mkdir higan-nightly
    - cp -a icarus/out/icarus higan-nightly/icarus
    - cp -a icarus/Database higan-nightly/
    - cp -a higan/out/higan higan-nightly/higan
    - cp -a higan/data/cheats.bml higan-nightly/
    - cp -a higan/systems/* higan-nightly/
  artifacts:
    paths:
      - higan-nightly/*
  cache:
    paths:
      - icarus/obj/*.o
      - higan/obj/*.o

windows-binaries:
  script:
    - apt update && apt -y install mingw-w64
    - sed -i -e 's/windres/x86_64-w64-mingw32-windres/' icarus/GNUmakefile higan/target-tomoko/GNUmakefile
    - make -C icarus platform=windows compiler="x86_64-w64-mingw32-g++ -lstatic-libgcc -static-libstdc++"
    - make -C higan platform=windows compiler="x86_64-w64-mingw32-g++ -lstatic-libgcc -static-libstdc++"
    - mkdir higan-nightly
    - cp -a icarus/out/icarus higan-nightly/icarus.exe
    - cp -a icarus/Database higan-nightly/
    - cp -a higan/out/higan higan-nightly/higan.exe
    - cp -a higan/data/cheats.bml higan-nightly/
    - cp -a higan/systems/* higan-nightly/
  artifacts:
    paths:
      - higan-nightly/*
