# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script: 
  #   - apt update && apt -y install make autoconf 
  script:
    - apt update && apt -y install build-essential libgtk2.0-dev libpulse-dev mesa-common-dev libgtksourceview2.0-dev libcairo2-dev libsdl1.2-dev libxv-dev libao-dev libopenal-dev libudev-dev
    - make -C icarus compiler=g++
    - make -C higan compiler=g++
    - mkdir -p artifacts/bin
    - mkdir -p artifacts/share/applications
    - make -C icarus prefix=../artifacts install
    - make -C higan prefix=../artifacts install
  artifacts:
    paths:
      - artifacts/*
  cache:
    paths:
      - icarus/obj/*.o
      - higan/obj/*.o
